<!-- BEGIN GCR Badge Code -->
<script src="https://apis.google.com/js/platform.js?onload=renderBadge" async defer></script>
<script>
    window.renderBadge = function() {
        var ratingBadgeContainer = document.createElement("div");
        document.body.appendChild(ratingBadgeContainer);
        window.gapi.load('ratingbadge', function() {
            window.gapi.ratingbadge.render(
                ratingBadgeContainer, {
                    "merchant_id": <?= $block->getGoogleMerchantId(); ?>,
                    "position": "<?= $block->getBadgePosition(); ?>"
                }
            );
        });
    }
</script>
<!-- END GCR Badge Code -->
<!-- BEGIN GCR Language Code -->
<script>
    window.___gcfg = {
        lang: '<?= $block->getLanguage(); ?>'
    };
</script>
<!-- END GCR Language Code -->